---
- hosts: localhost
  roles:
    - role: qemu_prepare
      when: native == "False"
    - role: qemu_run
      when: native == "False"
    - role: crossdev_check
      when: native == "False"

- hosts: target
  roles:
    - role: crossdev_getargs
      when: hostvars["localhost"]["native"] == "False" and hostvars["localhost"]["crossdev_check"]|failed

- hosts: localhost
  roles:
    - role: crossdev_run
      when: native == "False" and crossdev_check|failed
    - role: distcc_run
      when: native == "False"
