---
- hosts: localhost
  tasks:
    - name: add localhost to cross group
      add_host: name=localhost group=localhost_cross
      when: native == "False"
    - name: add target to cross group
      add_host: name=target group=target_cross
      when: native == "False"


- hosts: localhost_cross
  roles:
    - qemu_prepare
    - target_rundir_init
    - qemu_run
    - crossdev_check

- hosts: target_cross
  roles:
    - role: crossdev_getargs
      when: hostvars["localhost"]["crossdev_check"]|failed

- hosts: localhost_cross
  roles:
    - role: crossdev_run
      when: crossdev_check|failed
    - distcc_run
