---
- hosts: localhost
  roles:
    - image_setup
    - qemu_prepare
    - qemu_stop
    - qemu_run

- include: cross.yml
  when: native_arch != target_arch

- hosts: qemu
  roles:
    - packages_prepare
    - packages_flags
    - packages_install

- hosts: localhost
  roles:
    - qemu_stop
    - rootfs_copyoverlay
    - rootfs_pack
