---
# Setup and prepare phase
- hosts: localhost
  roles:
    - eval_variables
    - image_setup
    - target_stop
    - target_prepare
    - target_rundir_init

# Run phase
- include: "{{ playbook_dir }}/qemu_prepare_run_crossdev.yml"
  when: native == False
- include: "{{ playbook_dir }}/proot_prepare_and_run.yml"
  when: native == True

# Pre-Install and Install phase
- hosts: localhost
  roles:
    - role: copy_overlay
      overlay: pre_install_overlay
- hosts: target
  roles:
    - eval_variables
    - packages_flags
    - role: run_commands
      commands: "{{ pre_install_commands }}"
      when: pre_install_commands is defined
    - role: packages_install

# Post-Install phase
- hosts: localhost
  roles:
    - role: copy_overlay
      overlay: post_install_overlay
- hosts: target
  roles:
    - role: run_commands
      commands: "{{ post_install_commands }}"
      when: post_install_commands is defined

# Cleanup and Pack and Maintain image
- hosts: localhost
  roles:
    - target_stop
    - rootfs_pack
    - image_maintain
