---
- vars:
    target_arch: "{{ lookup('env','TARGET_ARCH') }}"
    target_arch_short: "{{ lookup('env','TARGET_ARCH_SHORT') }}"
    native_arch: "{{ lookup('env',' NATIVE_ARCH') }}"
    native_arch_short: "{{ lookup('env',' NATIVE_ARCH_SHORT') }}"

- hosts: localhost
  roles:
    - image_setup

- include: cross.yml
  when: native_arch.stdout != target_arch.stdout !=
