---
- hosts: localhost
  roles:
    - image_setup
    - qemu_prepare
    - qemu_run

- hosts: qemu
  roles:
    - crossdev_getargs

#- hosts: localhost
#  roles:
#    - crossdev_create
#    - distcc_run
