---
- name: Check if the image has already been set up
  shell: test -e {{ embedux_tmp }}/qemu_prepare/.done
  register: prepared
  ignore_errors: True

- include: qemu_prepare.yml
  when: prepared|failed
