---
- name: Download files needed to run qemu
  get_url: >
    dest={{ playbook_dir }}/files/{{ item.key }}
    url={{ item.value }}
  with_dict: downloads[target_arch_short]|default({})

- name: Unpack linux kernel
  unarchive: >
    copy=no
    src={{ playbook_dir }}/files/linux.tar
    dest={{ qemu_kernel_dir }}/

- name: Synchronize files
  synchronize: >
    src={{ playbook_dir }}/files/qemu_prepare/ dest={{ target_prepare_dir }}{{ embedux_tmp }}/files
    archive=no delete=no checksum=yes recursive=yes
    

- name: Run qemu_prepare.sh inside rootfs
  shell: sudo proot {{ qemu_emulator|default('') }} -b /etc/host.conf -b /etc/hosts -b /etc/resolv.conf -b /dev -b /sys -b /proc -b /tmp -0 -r {{ target_prepare_dir }}/ {{ embedux_tmp}}/files/qemu_prepare.sh

- name: Mark as prepared
  file: >
    path={{ embedux_tmp }}/.done_qemu_prepare
    state=touch
