---
- name: Create a btrfs snapshot for the prepare step
  shell: sudo btrfs subvolume snapshot {{ embedux_tmp }}/rootfs.btrfs.mnt/stage3 {{ embedux_tmp }}/rootfs.btrfs.mnt/qemu_prepare/

- name: Create and copy the SSH key
  shell: rm -Rf {{ embedux_tmp }}/image_setup/ssh_creds/*; ssh-keygen -N "" -f {{ embedux_tmp }}/image_setup/ssh_creds/qemu.id && cp {{ embedux_tmp }}/image_setup/ssh_creds/qemu.id.pub {{ files_dir }}/qemu_prepare/

- name: Create directories
  file: >
    state=directory
    path={{ item }}
  with_items:
    - "{{ embedux_tmp }}/qemu_prepare/"
    - "{{ embedux_tmp }}/rootfs.btrfs.mnt/qemu_prepare{{ embedux_tmp }}"

- name: Synchronize files
  synchronize: >
    src={{ playbook_dir }}/files/qemu_prepare/ dest={{ embedux_tmp }}/rootfs.btrfs.mnt/qemu_prepare{{ embedux_tmp }}/files
    archive=no delete=yes checksum=yes recursive=yes

- name: Run prepare.sh inside rootfs
  shell: sudo proot -q /usr/bin/qemu-arm -S {{ embedux_tmp }}/rootfs.btrfs.mnt/qemu_prepare/ {{ embedux_tmp}}/files/prepare.sh

- name: Mark as prepared
  file: >
    path={{ embedux_tmp }}/.done_qemu_prepare
    state=touch
