---
- name: Check if a snapshot already exists
  shell: test -e {{ embedux_tmp }}/rootfs.btrfs.mnt/copyoverlay
  register: snapshot_exists
  ignore_errors: True

- name: Remove the last snapshot 
  shell: sudo btrfs subvolume delete {{ embedux_tmp }}/rootfs.btrfs.mnt/copyoverlay
  when: snapshot_exists|success

- name: Create a btrfs snapshot for the prepare step
  shell: sudo btrfs subvolume snapshot {{ embedux_tmp }}/rootfs.btrfs.mnt/qemu_run {{ embedux_tmp }}/rootfs.btrfs.mnt/copyoverlay

- name: check if the overlay directory exists
  shell: test -d {{ pwd }}/overlay
  register: overlay
  ignore_errors: True

- name: Copy the overlay directory
  copy: >
    src={{ pwd }}/overlay/
    dest={{ embedux_tmp }}/rootfs.btrfs.mnt/copyoverlay/
  when: overlay|success
