---
- include: "{{ playbook_dir }}/roles/common/tasks/mount_image.yml"

- name: Remove existing SSH keys if any 
  shell: "sudo proot -b /etc/host.conf -b /etc/hosts -b /etc/resolv.conf -b /dev -b /sys -b /proc -r {{ target_run_dir }}/ rm /etc/sshd/*key*"
  ignore_errors: True

- name: Generate new SSH keys
  shell: "sudo proot -b /etc/host.conf -b /etc/hosts -b /etc/resolv.conf -b /dev -b /sys -b /proc -r {{ target_run_dir }}/ ssh-keygen -A"

- name: Start SSHd in target directory
  shell: "sudo proot -b {{ pkg_dir }}:/mnt/pkgdir -b /etc/host.conf -b /etc/hosts -b /etc/resolv.conf -b /dev -b /sys -b /proc -r {{ target_run_dir }}/ -b /usr/src sshd -4 -p 2222 &"
  async: 0
  poll: 0
  ignore_errors: True

- name: Wait for the SSHd to be reachable
  wait_for:
    port: 2222
    timeout: 30
    search_regex: ".*SSH.*"
  register: reachable
