---
- include: "{{ playbook_dir }}/roles/common/tasks/mount_image.yml"

- name: Remove existing SSH keys if any 
  shell: "proot -S {{ target_run_dir }} rm /etc/sshd/*key*"
  ignore_errors: True

- name: Generate new SSH keys
  shell: "proot -S {{ target_run_dir }} ssh-keygen -A"

- name: Start SSHd in target directory
  shell: "proot -S {{ target_run_dir }} -b /usr/src sshd -4 -p 2222"
  async: 999999999999
  poll: 0
