---
- name: Find target stage3 image
  shell: sudo docker images -q embedux/stage3-${TARGET_ARCH} | tail -n1
  register: stage3_image

- name: Create rootfs image file
  shell: qemu-img create -f raw {{ embedux_tmp }}/rootfs.btrfs.img 8G

- name: Format image file with btrfs
  shell: mkfs.btrfs {{ embedux_tmp }}/rootfs.btrfs.img

- name: Create directories
  file: >
    state=directory
    path={{ item }}
  with_items:
    - "{{ embedux_tmp }}/rootfs.btrfs.mnt"

- name: Create btrfs subvolume for stage3 
  shell: sudo btrfs subvolume create {{ embedux_tmp }}/rootfs.btrfs.mnt/stage3

- name: Extract the contents of the stage3 container
  shell: sudo docker save {{ stage3_image.stdout }} | tar --to-stdout -x --strip-components=1 -f - --wildcards */layer.tar | sudo tar -xp -f - -C {{ embedux_tmp }}/rootfs.btrfs.mnt/stage3/

- name: Mark as set up
  file: >
    path={{ embedux_tmp }}/.done_image_setup
    state=touch
