---
- name: Find target stage3 image
  shell: sudo docker images -q embedux/stage3-{{ target_arch }} | tail -n1
  register: stage3_image

- include: "{{ playbook_dir }}/roles/common/tasks/umount_image.yml"

- name: Create rootfs image file
  shell: qemu-img create -f raw {{ embedux_tmp }}/rootfs.btrfs.img 16G

- name: Format image file with btrfs
  shell: mkfs.btrfs --mixed {{ embedux_tmp }}/rootfs.btrfs.img

- name: Create directories
  file: >
    state=directory
    path={{ item }}
  with_items:
    - "{{ base_mount_dir }}"

- include: "{{ playbook_dir }}/roles/common/tasks/mount_image.yml"

- name: Create btrfs subvolume for stage3 
  shell: sudo btrfs subvolume create {{ stage3_dir }}

- name: Extract the contents of the stage3 container
  shell: sudo docker save {{ stage3_image.stdout }} | tar --to-stdout -x --strip-components=1 -f - --wildcards */layer.tar | sudo tar -xp -f - -C {{ stage3_dir }}/

- name: Mark as set up
  file: >
    path={{ embedux_tmp }}/.done_image_setup
    state=touch
