---
- name: Check if the image has already been set up
  shell: test -e {{ embedux_tmp }}/image_setup/.done
  register: prepared
  ignore_errors: True

- include: image_prepare.yml
  when: prepared|failed

- name: Mark as set up
  shell: touch {{ embedux_tmp }}/image_setup/.done
