---
- name: Check if the image has already been set up
  shell: test -e {{ embedux_tmp }}/.done_image_setup
  register: prepared
  ignore_errors: True

- include: image_prepare.yml
  when: prepared|failed

- name: Mount rootfs image
  mount: >
    src={{ embedux_tmp }}/rootfs.btrfs.img
    name={{ embedux_tmp }}/rootfs.btrfs.mnt 
  when: prepared|success
