---
- name: Check if it has been prepared
  shell: test -e /var/tmp/embedux/rootfs.btrfs.mnt/qemu-prepare/.prepared
  register: prepared
  ignore_errors: True

- name: Setup image for qemu
  shell: FILES_DIR={{ playbook_dir }}/files {{ playbook_dir }}/files/image_setup.sh
  when: prepared|failed

- name: copy qemu-prepare files
  synchronize: >
    src={{ playbook_dir }}/files/qemu-prepare/ dest=/var/tmp/embedux/rootfs.btrfs.mnt/qemu-prepare/tmp/files/
    archive=no delete=yes checksum=yes recursive=yes
  tags:
    - sync
