---
- name: Check if it has been prepared
  shell: test -e /var/tmp/embedux/rootfs.btrfs.mnt/qemu-prepare/.prepared
  register: prepared
  ignore_errors: True

- name: Setup image for qemu
  shell: FILES_DIR={{ playbook_dir }}/files {{ playbook_dir }}/files/image_setup.sh
  when: prepared|failed
