---
- name: Copy the container's kernel sources to the target
  shell: "sudo proot -b /etc/host.conf -b /etc/hosts -b /etc/resolv.conf -b /dev -b /sys -b /proc -b /usr/src:/tmp/usrsrc -r {{ target_prepare_dir }}/ rsync -a /tmp/usrsrc/ /usr/src"

- name: Retrieve installed gentoo-sources version
  shell: "qlist -IC gentoo-sources -v"
  register: gentoo_sources

- name: Mark virtual/linux-sources as provided in the target
  shell: 'sudo proot -b /etc/host.conf -b /etc/hosts -b /etc/resolv.conf -b /dev -b /sys -b /proc -r {{ target_prepare_dir }}/ bash -c "mkdir -p /etc/portage/profile; echo virtual/linux-sources-1 >> /etc/portage/profile/package.provided"'

- name: Build and install kernel modules in the target
  shell: 'sudo proot -b /etc/host.conf -b /etc/hosts -b /etc/resolv.conf -b /dev -b /sys -b /proc -r {{ target_prepare_dir }}/ bash -c "pushd /usr/src/linux make olddefconfig; make -j8 modules; make modules_install; popd"'

- name: Mark as prepared
  file: >
    path={{ embedux_tmp }}/.done_proot_prepare
    state=touch
