---
- name: Run script that estimates the crossdev arguments
  script: getargs.sh
  register: crossdev_getargs
  delegate_to: qemu

- name: Set crossdev_args fact
  set_fact:
    crossdev_args: "{{ crossdev_getargs.stdout }}"
