---
- name: Check if the VM is reachable
  wait_for:
    port: 2222
    timeout: 30
    search_regex: ".*SSH.*"
  ignore_errors: True
  register: reachable

- include: "{{ playbook_dir }}/roles/common/tasks/qemu_kill.yml"
- include: "{{ playbook_dir }}/roles/common/tasks/mount_image.yml"
- include: qemu_run.yml
