---
- name: Check if the VM is reachable
  wait_for:
    port: 2222
    timeout: 30
    search_regex: ".*SSH.*"
  ignore_errors: True
  register: reachable

- include: qemu_run.yml
  when: reachable|failed
