---
- name: Check for PID file
  shell: cat {{ qemu_pidfile }}
  register: qemu_pid
  ignore_errors: True

- name: Check if qemu is still running
  shell: kill {{ qemu_pid.stdout }}
  when: qemu_pid
  ignore_errors: True

- name: Make sure the image is not mounted
  shell: sudo umount {{ embedux_tmpdir }}/rootfs.btrfs.img
  register: umount
  failed_when: umount.rc == 0
  ignore_errors: True

- name: Run emulator in background
  command: "IMAGE={{ qemu_imagefile }} PIDFILE={{ qemu_pidfile }} KERNEL_DIR={{ qemu_kernel_dir }} \ 
            {{ playbook_dir }}/roles/qemu_run/files/qemu_run.sh"
  
- name: Wait for the VM to boot
  command: "{{ playbook_dir }}/roles/qemu_run/files/wait_for_vm.py"
