---
- include: "{{ playbook_dir }}/roles/common/tasks/qemu_kill.yml"
- include: "{{ playbook_dir }}/roles/common/tasks/mount_image.yml"

- name: Check if a snapshot already exists
  shell: test -e {{ embedux_tmp }}/rootfs.btrfs.mnt/qemu_run
  register: snapshot_exists
  ignore_errors: True

- name: Remove the last snapshot 
  shell: sudo btrfs subvolume delete {{ embedux_tmp }}/rootfs.btrfs.mnt/qemu_run
  when: snapshot_exists|success

- name: Create a btrfs snapshot for the prepare step
  shell: sudo btrfs subvolume snapshot {{ embedux_tmp }}/rootfs.btrfs.mnt/qemu_prepare {{ embedux_tmp }}/rootfs.btrfs.mnt/qemu_run

- include: "{{ playbook_dir }}/roles/common/tasks/umount_image.yml"

- name: Run emulator in background
  shell: "MACHINE_ARG={{ machine_arg[target_arch_short] }} IMAGE={{ qemu_imagefile }} PIDFILE={{ qemu_pidfile }} KERNEL_DIR={{ qemu_kernel_dir }} \ 
          {{ playbook_dir }}/roles/qemu_run/files/qemu_run.sh"
  
- name: Wait for the VM to boot
  shell: "{{ playbook_dir }}/roles/qemu_run/files/wait_for_vm.py"
