---
- name: Check for PID file
  shell: cat {{ qemu_pidfile }}
  register: qemu_pid
  ignore_errors: True

- name: Kill the qemu process and clean up the pidfile
  shell: kill -9 {{ qemu_pid.stdout }}; -e rm {{ qemu_pidfile }}
  when: qemu_pid.stdout != ""

- name: Check if the image is mounted
  shell: mount | grep {{ embedux_tmp }}/rootfs.btrfs.img
  register: mounted
  ignore_errors: True

- name: Make sure the image is not mounted
  shell: sudo umount {{ embedux_tmp }}/rootfs.btrfs.img
  when: mounted.stdout != ""

- name: Run emulator in background
  shell: "IMAGE={{ qemu_imagefile }} PIDFILE={{ qemu_pidfile }} KERNEL_DIR={{ qemu_kernel_dir }} \ 
          {{ playbook_dir }}/roles/qemu_run/files/qemu_run.sh"
  
- name: Wait for the VM to boot
  shell: "{{ playbook_dir }}/roles/qemu_run/files/wait_for_vm.py"
