---
- name: Check for running distccd
  shell: ps aux | grep distccd | wc -l
  register: distccd_pid
  ignore_errors: True

- name: Kill the distccd process and clean up the pidfile
  shell: pkill -9 distccd
  when: distccd_pid.stdout != "0"

- name: Run distccd
  shell: "distccd --daemon --port 3632 --log-level notice \
          --log-file {{ distccd_logfile }} -N 0 --allow 127.0.0.1"
