---
- name: Generate a cross toolchain
  shell: sudo crossdev {{ hostvars["target"]["crossdev_args"] }}

- name: Mark crossdev as run
  file: >
    path={{ embedux_tmp }}/.done_crossdev_run
    state=touch
