---
- name: Run script that estimates the crossdev arguments
  script: /tmp/getargs.sh
  register: crossdev_args
  delegate_to: qemu

- name: Generate a cross toolchain
  shell: sudo crossdev {{ hostvars["qemu"]["crossdev_args"].stdout }}

- name: Mark crossdev as run
  file: >
    path={{ embedux_tmp }}/.done_crossdev_run
    state=touch
