---
- hosts: localhost
  roles:
    - role: qemu_prepare
    - role: qemu_run
    - role: crossdev_check

- hosts: target
  roles:
    - role: crossdev_getargs
      when: hostvars["localhost"]["crossdev_check"]|failed

- hosts: localhost
  roles:
    - role: crossdev_run
      when: crossdev_check|failed
    - distcc_run
