---
- name: emerge using autounmask
  shell: emerge --autounmask-write=y -nkb {{ atom }}
  register: autounmasked
  ignore_errors: True

- name: run etc-update in automode
  shell: etc-update --automode -5
  when: autounmasked|failed

- name: emerge regularely
  shell: emerge -nkb {{ atom }}
  when: autounmasked|failed
