---
- name: Render image fstab template
  template: >
    src=image_fstab.j2
    dest={{ playbook_dir}}/files/image_fstab

- name: Mount rootfs image
  sudo: yes
  mount:
    fstab: "{{ playbook_dir }}/files/image_fstab"
    src: "{{ embedux_tmp }}/rootfs.btrfs.img"
    name: "{{ embedux_tmp }}/rootfs.btrfs.img"
    fstype: none
    state: mounted
