---
- name: Check if image is mounted
  shell: mount | grep {{ base_mount_dir }} | wc -l
  register: mounted
  
- name: Mount rootfs image
  shell: sudo mount {{ embedux_tmp }}/rootfs.btrfs.img {{ base_mount_dir }}
  when: mounted.stdout == "0"
