---
- name: Render image fstab template
  template: >
    src=image_fstab.j2
    dest={{ playbook_dir}}/files/image_fstab

- name: Mount rootfs image
  mount: >
    src={{ embedux_tmp }}/rootfs.btrfs.img
    name={{ embedux_tmp }}/rootfs.btrfs.mnt 
    fstype={{ playbook_dir}}/files/image_fstab
    state=mounted
