---
- name: Check if image is mounted
  shell: mount | grep rootfs | wc -l
  register: mounted
  
- name: Mount rootfs image
  shell: sudo mount {{ embedux_tmp }}/rootfs.btrfs.img {{ embedux_tmp }}/rootfs.btrfs.mnt
  when: mounted.stdout == "0"
