---
- name: Check if image is mounted
  shell: mount | grep rootfs  wc -l
  register: mounted
  
- name: Mount rootfs image
  shell: sudo {{ embedux_tmp }}/rootfs.btrfs.img {{ embedux_tmp }}/rootfs.btrfs.img
  when: mounted.stdout == "0"
