---
- name: Check if image is mounted
  shell: mount | grep {{ base_mount_dir }} | wc -l
  register: mounted
  
- name: Unmount rootfs image
  shell: sudo umount {{ base_mount_dir }}
  when: mounted.stdout != "0"
