---
- name: Make sure output folder exists
  file: >
    path={{ pwd }}/output
    state=directory

- name: Pack the rootfs
  shell: >
    "sudo tar -cjp -f {{ pwd }}/output/$(git rev-parse --abbrev-ref HEAD)_$(date '+%Y%m%d%H%M%S')_$(git rev-parse --short HEAD)_rootfs.tbz2 \
      --exclude='/usr/portage/distfiles/*' \
      --exclude='/var/tmp/*' \
      --exclude '/root/*' \
      --exclude='/home/*' \
      --exclude='/etc/ssh/*key*' \
      -C {{ embedux_tmp }}/rootfs.btrfs.mnt/copyoverlay/ ."

- include: "{{ playbook_dir }}/roles/common/tasks/btrfs_balance.yml"
  path: "{{ embedux_tmp }}/rootfs.btrfs.mnt/"
