---
- name: Make sure output folder exists
  file: >
    path={{ pwd }}/output
    state=directory

- name: Estimate rootfs filename
  shell: "cd {{ pwd }} && echo $(git rev-parse --abbrev-ref HEAD)_$(date '+%Y%m%d%H%M%S')_$(git rev-parse --short HEAD)_rootfs.tbz2"
  register: rootfs_filename

- name: Pack the rootfs
  shell: "sudo tar -cjp -f {{ pwd }}/output/{{ rootfs_filename.stdout }} \
      -C {{ target_run_dir }} . \
      --exclude='./usr/src/*' \
      --exclude='./usr/portage/distfiles/*' \
      --exclude='./var/tmp/*' \
      --exclude='./root/*' \
      --exclude='./home/*' \
      --exclude='./etc/fstab' \
      --exclude='./etc/ssh/*key*' \
      --exclude='./etc/local.d/send_signal_from_vm.py.start' \
      --exclude='./mnt/*'"

